version: "3.9"

services:

  backend:
    build: ./backend
    container_name: nakhlah_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - ai
    networks:
      - nakhlah_net

  ai:
    build: ./ai
    container_name: nakhlah_ai
    ports:
      - "8001:8001"
    networks:
      - nakhlah_net

networks:
  nakhlah_net:
    driver: bridge