// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyRcPHn24MCUPDSH1Vr6FSuA1nXS7Gu1k',
    appId: '1:624405399465:web:f5eb9e7e2834a84f9826b8',
    messagingSenderId: '624405399465',
    projectId: 'nakhlah-c5a65',
    authDomain: 'nakhlah-c5a65.firebaseapp.com',
    storageBucket: 'nakhlah-c5a65.firebasestorage.app',
    measurementId: 'G-9B55M1W8ZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvWxfFUrHGWSe0cQL-pvVitX_yE50WLvI',
    appId: '1:624405399465:android:bdb3bc7eb8b2f2079826b8',
    messagingSenderId: '624405399465',
    projectId: 'nakhlah-c5a65',
    storageBucket: 'nakhlah-c5a65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRpBrtlpXiebo8AvhJO2EbiKdzuxJdlBc',
    appId: '1:624405399465:ios:171bfc5c03008a219826b8',
    messagingSenderId: '624405399465',
    projectId: 'nakhlah-c5a65',
    storageBucket: 'nakhlah-c5a65.firebasestorage.app',
    iosBundleId: 'com.example.nakhlah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRpBrtlpXiebo8AvhJO2EbiKdzuxJdlBc',
    appId: '1:624405399465:ios:171bfc5c03008a219826b8',
    messagingSenderId: '624405399465',
    projectId: 'nakhlah-c5a65',
    storageBucket: 'nakhlah-c5a65.firebasestorage.app',
    iosBundleId: 'com.example.nakhlah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyRcPHn24MCUPDSH1Vr6FSuA1nXS7Gu1k',
    appId: '1:624405399465:web:09ab1f86c9e898c29826b8',
    messagingSenderId: '624405399465',
    projectId: 'nakhlah-c5a65',
    authDomain: 'nakhlah-c5a65.firebaseapp.com',
    storageBucket: 'nakhlah-c5a65.firebasestorage.app',
    measurementId: 'G-D697D2TQXS',
  );
}
